apiVersion: v1
kind: ReplicationController
metadata:
  name: zulip-1
  labels:
    version: 2.1.2-0
    app: zulip
spec:
  replicas: 1
  selector:
    version: 2.1.2-0
    app: zulip
  template:
    metadata:
      labels:
        version: 2.1.2-0
        app: zulip
    spec:
      containers:
      - name: redis
        image: redis:alpine
        resources:
          limits:
            cpu: 50m
        command: ["/bin/sh"]
        args: ["-c", "echo requirepass $REDIS_PASSWORD > /etc/redis.conf; exec redis-server /etc/redis.conf"]
        env:
        - name: REDIS_PASSWORD
          value: 'REPLACE_WITH_SECURE_REDIS_PASSWORD'
        volumeMounts:
          - name: redis-pv
            mountPath: /data
      - name: memcached
        image: memcached:alpine
        resources:
          limits:
            cpu: 75m
            memory: 768Mi
        command: ["/bin/sh"]
        args: ["-c", "echo mech_list: plain > $SASL_CONF_PATH; echo zulip@$HOSTNAME:$MEMCACHED_PASSWORD > $MEMCACHED_SASL_PWDB; exec memcached -S"]
        env:
        - name: SASL_CONF_PATH
          value: '/home/memcache/memcached.conf'
        - name: MEMCACHED_SASL_PWDB
          value: '/home/memcache/memcached-sasl-db'
        - name: MEMCACHED_PASSWORD
          value: 'REPLACE_WITH_SECURE_MEMCACHED_PASSWORD'
      - name: rabbitmq
        image: rabbitmq:alpine
        resources:
          limits:
            cpu: 75m
            memory: 768Mi
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: "zulip"
        - name: RABBITMQ_DEFAULT_PASS
          value: "REPLACE_WITH_SECURE_RABBITMQ_PASSWORD"
        volumeMounts:
          - name: rabbitmq-pv
            mountPath: /var/lib/rabbitmq
      - name: postgresql
        image: zulip/zulip-postgresql:latest
        resources:
          limits:
            cpu: 80m
            memory: 768Mi
        volumeMounts:
          - name: postgresql-pv
            mountPath: /var/lib/postgresql/data
      - name: zulip
        image: zulip/docker-zulip:2.1.2-0
        resources:
          limits:
            cpu: 100m
            memory: 3584Mi
        env:
        # Please take a look at the environment variables in docker-compose.yml for all required env variables!
        - name: DB_HOST
          value: 'localhost'
        - name: MEMCACHED_HOST
          value: 'localhost'
        - name: REDIS_HOST
          value: 'localhost'
        - name: RABBITMQ_HOST
          value: 'localhost'
        - name: ZULIP_AUTH_BACKENDS
          value: 'EmailAuthBackend'
        - name: SECRETS_email_password
          value: '123456789'
        - name: SETTING_EXTERNAL_HOST
          value: 'localhost'
        - name: SETTING_ZULIP_ADMINISTRATOR
          value: 'admin@example.com'
        - name: SETTING_EMAIL_HOST
          value: ''  # E.g. 'smtp.example.com'
        - name: SETTING_EMAIL_HOST_USER
          value: 'noreply@example.com'
        - name: ZULIP_USER_EMAIL
          value: 'example@example.com'
        - name: ZULIP_USER_DOMAIN
          value: 'example.com'
        - name: ZULIP_USER_PASS
          value: '123456789'
        - name: SECRETS_secret_key
          value: 'REPLACE_WITH_SECURE_SECRET_KEY'
        # These should match the passwords configured above
        # except for Postgres pass which is set during 'zulip-postgresql' image build.
        - name: SECRETS_postgres_password
          value: 'zulip'
        - name: SECRETS_rabbitmq_password
          value: 'REPLACE_WITH_SECURE_RABBITMQ_PASSWORD'
        - name: SECRETS_memcached_password
          value: 'REPLACE_WITH_SECURE_MEMCACHED_PASSWORD'
        - name: SECRETS_redis_password
          value: 'REPLACE_WITH_SECURE_REDIS_PASSWORD'
        - name: SSL_CERTIFICATE_GENERATION
          value: 'self-signed'
        # Uncomment this when configuring the mobile push notifications service
        # - name: SETTING_PUSH_NOTIFICATION_BOUNCER_URL
        # value: 'https://push.zulipchat.com'
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        - containerPort: 443
          name: https
          protocol: TCP
        volumeMounts:
          - name: zulip-pv
            mountPath: /data
#        livenessProbe:
#          httpGet:
#            path: /login
#            port: 443
#            scheme: HTTP
#          initialDelaySeconds: 120
#          timeoutSeconds: 12
      volumes:
      - name: redis-pv
        persistentVolumeClaim:
          claimName: redis-pv-claim
      - name: rabbitmq-pv
        persistentVolumeClaim:
          claimName: rabbitmq-pv-claim
      - name: postgresql-pv
        persistentVolumeClaim:
          claimName: postgresql-pv-claim
      - name: zulip-pv
        persistentVolumeClaim:
          claimName: zulip-pv-claim
