apiVersion: v2
description: zulipchat
name: zulip
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.2.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "4.7-0"
dependencies:
  - name: memcached
    repository: https://charts.bitnami.com/bitnami
    tags:
      - memcached
    version: 5.15.8
  - name: rabbitmq
    repository: https://charts.bitnami.com/bitnami
    tags:
      - rabbitmq
    version: 8.24.3
  - name: redis
    repository: https://charts.bitnami.com/bitnami
    tags:
      - redis
    version: 15.5.5
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    tags:
      - postgresql
    version: 10.13.8
