
{{- define "zulip.template.service" -}}
{{ println "" }}
{{ println "---" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "zulip.fullname.withName" . }}
  labels:
    {{- include "zulip.labels.withName" . | nindent 4 }}
spec:
  type: {{ .subvalues.serviceType }}
  ports:
    - port: {{ .subvalues.port }}
      targetPort: {{ .subvalues.port }}
      protocol: TCP
      name: default
  selector:
    {{- include "zulip.selectorLabels.withName" . | nindent 4 }}
{{- end }}
