apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-post-setup-scripts"
  labels:
    {{- include "zulip.labels" . | nindent 4 }}
data:
  {{- range $scriptName, $scriptContents := .Values.postSetup.scripts }}
  {{ $scriptName }}: |
    {{- $scriptContents | nindent 4 }}
  {{- end }}
  {{- if .Values.zulip.smokeScreen.whitelistedAddresses }}
  __zulip_smokescreen_whitelist.sh: |
    #!/bin/bash

    sed -ri \
        "s/(command.*)/\1
        {{- range .Values.zulip.smokeScreen.whitelistedAddresses }} --allow-address {{ . }}{{ end -}}
        /" \
        /etc/supervisor/conf.d/zulip/smokescreen.conf

  {{- end }}
