apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "zulip.fullname" . }}
  labels:
    {{- include "zulip.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "zulip.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "zulip.fullname" . }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "zulip.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "zulip.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          volumeMounts:
            - name: {{ include "zulip.fullname" . }}-persistent-storage
              mountPath: /data
          env:
            - name: DB_HOST
              value: "{{ template "postgresql.primary.fullname" .Subcharts.postgresql }}"
            - name: DB_HOST_PORT
              value: "{{ template "postgresql.port" .Subcharts.postgresql }}"
            - name: DB_USER
              value: "postgres"
            - name: SETTING_MEMCACHED_LOCATION
              value: "{{ template "memcached.fullname" .Subcharts.memcached }}:11211"
            - name: SETTING_RABBITMQ_HOST
              value: "{{ template "rabbitmq.fullname" .Subcharts.rabbitmq }}"
            - name: SETTING_REDIS_HOST
              value: "{{ template "common.names.fullname" .Subcharts.redis }}-headless"
            - name: SECRETS_rabbitmq_password 
              value: "{{ .Values.rabbitmq.auth.password }}"
            - name: SECRETS_postgres_password
              value: "{{ .Values.postgresql.postgresqlPassword }}"
            - name: SECRETS_memcached_password
              value: "{{ .Values.memcached.memcachedPassword }}"
            - name: SECRETS_redis_password
              value: "{{ .Values.redis.auth.password }}"
            - name: SECRETS_secret_key
              value: "{{ .Values.zulip.password }}"
            {{- range $key, $value := .Values.zulip.environment }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: {{ include "zulip.fullname" . }}-persistent-storage
          persistentVolumeClaim:
            claimName: {{ if .Values.zulip.persistence.existingClaim }}{{ .Values.zulip.persistence.existingClaim }}{{- else }}{{ template "zulip.fullname" . }}-data{{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
