
{{- define "zulip.default.routing.envs" -}}
environment:
  DB_HOST: {{ include "zulip.fullname.withName" (dict "name" "postgresql" "root" .) }}
  DB_HOST_PORT: 5432
  DB_USER: zulip
  SETTING_MEMCACHED_LOCATION: {{ include "zulip.fullname.withName" (dict "name" "memcached" "root" . ) }}:11211
  SETTING_RABBITMQ_HOST: {{ include "zulip.fullname.withName" (dict "name" "rabbitmq" "root" . ) }}
  SETTING_REDIS_HOST: {{ include "zulip.fullname.withName" (dict "name" "redis" "root" . ) }}
  SECRETS_rabbitmq_password: {{ .Values.rabbitmq.password }}
  SECRETS_postgres_password: {{ .Values.postgresql.password }}
  SECRETS_memcached_password: {{ .Values.memcached.password }}
  SECRETS_redis_password: {{ .Values.redis.password }}
  SECRETS_secret_key: {{ .Values.zulip.password }}
{{- end }}


{{- define "zulip.zulip.subvalues" -}}
{{- with .Values.zulip }}
{{- toYaml . }}
{{- end }}
serviceType: ClusterIP
port: 80

{{- $envs := mergeOverwrite .Values.zulip.environment ((include "zulip.default.routing.envs" .) | fromYaml).environment}}
env:
  {{- range $key, $value := $envs }}
  - name: {{ $key }}
    value: {{ $value | quote }}
  {{- end }}
{{- end }}

{{- $subvalues := (include "zulip.zulip.subvalues" .) | fromYaml }}

{{- $data := dict "name" "zulip" "subvalues" $subvalues "root" . -}}

{{- include "zulip.template.deployment" $data }}
{{- include "zulip.template.service" $data }}
{{- include "zulip.template.pvc" $data }}

