---
name: Publish Docker Image to GHCR (versioned + :latest)

on:
  push:
    tags:
      - '*'

jobs:
  multiarch-image:
    uses: ./.github/workflows/build-and-push-ghcr-common.yml
    secrets: inherit
    with:
      allow-push-latest-tag: true
